/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    pages: Page;
    "blog-posts": BlogPost;
    forms: Form;
    "form-submissions": FormSubmission;
    "payload-kv": PayloadKv;
    "payload-jobs": PayloadJob;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    "blog-posts": BlogPostsSelect<false> | BlogPostsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    "form-submissions":
      | FormSubmissionsSelect<false>
      | FormSubmissionsSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-jobs": PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ("false" | "none" | "null")
    | false
    | null
    | ("en" | "nl")
    | ("en" | "nl")[];
  globals: {
    navigation: Navigation;
    footer: Footer;
    home: Home;
    blog: Blog;
    "privacy-policy": PrivacyPolicy;
    "cookie-policy": CookiePolicy;
    "terms-and-conditions": TermsAndCondition;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    "privacy-policy": PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    "cookie-policy": CookiePolicySelect<false> | CookiePolicySelect<true>;
    "terms-and-conditions":
      | TermsAndConditionsSelect<false>
      | TermsAndConditionsSelect<true>;
  };
  locale: "en" | "nl";
  user: User & {
    collection: "users";
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for the file (for SEO purposes).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    openGraph?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: ("developer" | "admin") | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  blocks?:
    | (
        | TextAndImageBlock
        | FormBlock
        | TextBlock
        | CardsBlock
        | VisualBlock
        | ProcessBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically generated from the title field
   */
  slug?: string | null;
  /**
   * URL path for the page (e.g., /about or /nl/diensten/websites)
   */
  url?: string | null;
  /**
   * Automatically generated from URL field without locale prefix
   */
  urlWithoutLocale?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextAndImageBlock".
 */
export interface TextAndImageBlock {
  showHeading?: boolean | null;
  heading?: {
    icon?: (number | null) | Media;
    text?: string | null;
    centered?: boolean | null;
  };
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  showButton?: boolean | null;
  button?: {
    variant:
      | "purpleButton"
      | "whiteButton"
      | "darkButton"
      | "transparentButton";
    text: string;
    customHref?: boolean | null;
    href?: string | null;
    linkType?:
      | (
          | "home"
          | "blog"
          | "page"
          | "blog-post"
          | "privacy-policy"
          | "cookie-policy"
          | "terms-and-conditions"
        )
      | null;
    page?: {
      relationTo: "pages";
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: "blog-posts";
      value: number | BlogPost;
    } | null;
    newTab?: boolean | null;
    centered?: boolean | null;
  };
  image?: (number | null) | Media;
  imageSide?: ("left" | "right") | null;
  width?: ("small" | "medium" | "large") | null;
  dark?: boolean | null;
  paddingTop?: ("none" | "small" | "medium" | "large") | null;
  paddingBottom?: ("none" | "small" | "medium" | "large") | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "text-and-image-block";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  minRead?: number | null;
  image?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically generated from the title field
   */
  slug?: string | null;
  /**
   * Automatically generated from the slug field
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  /**
   * Select the form that should be shown
   */
  form: number | Form;
  fullScreen?: boolean | null;
  showHeading?: boolean | null;
  heading?: {
    icon?: (number | null) | Media;
    text?: string | null;
    centered?: boolean | null;
  };
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  showButton?: boolean | null;
  button?: {
    variant:
      | "purpleButton"
      | "whiteButton"
      | "darkButton"
      | "transparentButton";
    text: string;
    customHref?: boolean | null;
    href?: string | null;
    linkType?:
      | (
          | "home"
          | "blog"
          | "page"
          | "blog-post"
          | "privacy-policy"
          | "cookie-policy"
          | "terms-and-conditions"
        )
      | null;
    page?: {
      relationTo: "pages";
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: "blog-posts";
      value: number | BlogPost;
    } | null;
    newTab?: boolean | null;
    centered?: boolean | null;
  };
  formSide?: ("left" | "right") | null;
  dark?: boolean | null;
  paddingTop?: ("none" | "small" | "medium" | "large") | null;
  paddingBottom?: ("none" | "small" | "medium" | "large") | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "form-block";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  description?: string | null;
  fields?:
    | {
        name?: string | null;
        type?:
          | (
              | ""
              | "text"
              | "textarea"
              | "email"
              | "tel"
              | "number"
              | "select"
              | "checkbox"
              | "radio"
              | "date"
              | "time"
              | "datetime-local"
              | "file"
              | "url"
              | "password"
              | "hidden"
              | "range"
              | "color"
              | "search"
            )
          | null;
        options?:
          | {
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        multiSelect?: boolean | null;
        maxNumFiles?: number | null;
        maxMBs?: number | null;
        includeCheckboxLink?: boolean | null;
        checkboxLink?: {
          textWithLink?: string | null;
          customHref?: boolean | null;
          href?: string | null;
          linkType?:
            | (
                | "home"
                | "blog"
                | "page"
                | "blog-post"
                | "privacy-policy"
                | "cookie-policy"
                | "terms-and-conditions"
              )
            | null;
          page?: {
            relationTo: "pages";
            value: number | Page;
          } | null;
          blogPost?: {
            relationTo: "blog-posts";
            value: number | BlogPost;
          } | null;
          newTab?: boolean | null;
        };
        required?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  showHeading?: boolean | null;
  heading?: {
    icon?: (number | null) | Media;
    text?: string | null;
    centered?: boolean | null;
  };
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  showButton?: boolean | null;
  button?: {
    variant:
      | "purpleButton"
      | "whiteButton"
      | "darkButton"
      | "transparentButton";
    text: string;
    customHref?: boolean | null;
    href?: string | null;
    linkType?:
      | (
          | "home"
          | "blog"
          | "page"
          | "blog-post"
          | "privacy-policy"
          | "cookie-policy"
          | "terms-and-conditions"
        )
      | null;
    page?: {
      relationTo: "pages";
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: "blog-posts";
      value: number | BlogPost;
    } | null;
    newTab?: boolean | null;
    centered?: boolean | null;
  };
  width?: ("small" | "medium" | "large") | null;
  dark?: boolean | null;
  paddingTop?: ("none" | "small" | "medium" | "large") | null;
  paddingBottom?: ("none" | "small" | "medium" | "large") | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "text-block";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock".
 */
export interface CardsBlock {
  cards?:
    | {
        icon?: (number | null) | Media;
        text?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ("ltr" | "rtl") | null;
            format:
              | "left"
              | "start"
              | "center"
              | "right"
              | "end"
              | "justify"
              | "";
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        showButton?: boolean | null;
        button?: {
          variant:
            | "purpleButton"
            | "whiteButton"
            | "darkButton"
            | "transparentButton";
          text: string;
          customHref?: boolean | null;
          href?: string | null;
          linkType?:
            | (
                | "home"
                | "blog"
                | "page"
                | "blog-post"
                | "privacy-policy"
                | "cookie-policy"
                | "terms-and-conditions"
              )
            | null;
          page?: {
            relationTo: "pages";
            value: number | Page;
          } | null;
          blogPost?: {
            relationTo: "blog-posts";
            value: number | BlogPost;
          } | null;
          newTab?: boolean | null;
          centered?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  dark?: boolean | null;
  paddingTop?: ("none" | "small" | "medium" | "large") | null;
  paddingBottom?: ("none" | "small" | "medium" | "large") | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "cards-block";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisualBlock".
 */
export interface VisualBlock {
  visual?: (number | null) | Media;
  showSocialMediaLinks?: boolean | null;
  socialMediaLinks?:
    | {
        icon?: (number | null) | Media;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  showButton?: boolean | null;
  button?: {
    variant:
      | "purpleButton"
      | "whiteButton"
      | "darkButton"
      | "transparentButton";
    text: string;
    customHref?: boolean | null;
    href?: string | null;
    linkType?:
      | (
          | "home"
          | "blog"
          | "page"
          | "blog-post"
          | "privacy-policy"
          | "cookie-policy"
          | "terms-and-conditions"
        )
      | null;
    page?: {
      relationTo: "pages";
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: "blog-posts";
      value: number | BlogPost;
    } | null;
    newTab?: boolean | null;
    centered?: boolean | null;
  };
  dark?: boolean | null;
  paddingTop?: ("none" | "small" | "medium" | "large") | null;
  paddingBottom?: ("none" | "small" | "medium" | "large") | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "visual-block";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock".
 */
export interface ProcessBlock {
  steps?:
    | {
        number?: string | null;
        title?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  dark?: boolean | null;
  paddingTop?: ("none" | "small" | "medium" | "large") | null;
  paddingBottom?: ("none" | "small" | "medium" | "large") | null;
  id?: string | null;
  blockName?: string | null;
  blockType: "process-block";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  uploads?:
    | {
        field: string;
        files: (number | Media)[];
        id?: string | null;
      }[]
    | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: "inline" | "schedulePublish";
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: "failed" | "succeeded";
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ("inline" | "schedulePublish") | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "pages";
        value: number | Page;
      } | null)
    | ({
        relationTo: "blog-posts";
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: "forms";
        value: number | Form;
      } | null)
    | ({
        relationTo: "form-submissions";
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        openGraph?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  blocks?:
    | T
    | {
        "text-and-image-block"?: T | TextAndImageBlockSelect<T>;
        "form-block"?: T | FormBlockSelect<T>;
        "text-block"?: T | TextBlockSelect<T>;
        "cards-block"?: T | CardsBlockSelect<T>;
        "visual-block"?: T | VisualBlockSelect<T>;
        "process-block"?: T | ProcessBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  slug?: T;
  url?: T;
  urlWithoutLocale?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextAndImageBlock_select".
 */
export interface TextAndImageBlockSelect<T extends boolean = true> {
  showHeading?: T;
  heading?:
    | T
    | {
        icon?: T;
        text?: T;
        centered?: T;
      };
  text?: T;
  showButton?: T;
  button?:
    | T
    | {
        variant?: T;
        text?: T;
        customHref?: T;
        href?: T;
        linkType?: T;
        page?: T;
        blogPost?: T;
        newTab?: T;
        centered?: T;
      };
  image?: T;
  imageSide?: T;
  width?: T;
  dark?: T;
  paddingTop?: T;
  paddingBottom?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  fullScreen?: T;
  showHeading?: T;
  heading?:
    | T
    | {
        icon?: T;
        text?: T;
        centered?: T;
      };
  text?: T;
  showButton?: T;
  button?:
    | T
    | {
        variant?: T;
        text?: T;
        customHref?: T;
        href?: T;
        linkType?: T;
        page?: T;
        blogPost?: T;
        newTab?: T;
        centered?: T;
      };
  formSide?: T;
  dark?: T;
  paddingTop?: T;
  paddingBottom?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  showHeading?: T;
  heading?:
    | T
    | {
        icon?: T;
        text?: T;
        centered?: T;
      };
  text?: T;
  showButton?: T;
  button?:
    | T
    | {
        variant?: T;
        text?: T;
        customHref?: T;
        href?: T;
        linkType?: T;
        page?: T;
        blogPost?: T;
        newTab?: T;
        centered?: T;
      };
  width?: T;
  dark?: T;
  paddingTop?: T;
  paddingBottom?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock_select".
 */
export interface CardsBlockSelect<T extends boolean = true> {
  cards?:
    | T
    | {
        icon?: T;
        text?: T;
        showButton?: T;
        button?:
          | T
          | {
              variant?: T;
              text?: T;
              customHref?: T;
              href?: T;
              linkType?: T;
              page?: T;
              blogPost?: T;
              newTab?: T;
              centered?: T;
            };
        id?: T;
      };
  dark?: T;
  paddingTop?: T;
  paddingBottom?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisualBlock_select".
 */
export interface VisualBlockSelect<T extends boolean = true> {
  visual?: T;
  showSocialMediaLinks?: T;
  socialMediaLinks?:
    | T
    | {
        icon?: T;
        href?: T;
        id?: T;
      };
  showButton?: T;
  button?:
    | T
    | {
        variant?: T;
        text?: T;
        customHref?: T;
        href?: T;
        linkType?: T;
        page?: T;
        blogPost?: T;
        newTab?: T;
        centered?: T;
      };
  dark?: T;
  paddingTop?: T;
  paddingBottom?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProcessBlock_select".
 */
export interface ProcessBlockSelect<T extends boolean = true> {
  steps?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  dark?: T;
  paddingTop?: T;
  paddingBottom?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  minRead?: T;
  image?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  slug?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  fields?:
    | T
    | {
        name?: T;
        type?: T;
        options?:
          | T
          | {
              value?: T;
              id?: T;
            };
        multiSelect?: T;
        maxNumFiles?: T;
        maxMBs?: T;
        includeCheckboxLink?: T;
        checkboxLink?:
          | T
          | {
              textWithLink?: T;
              customHref?: T;
              href?: T;
              linkType?: T;
              page?: T;
              blogPost?: T;
              newTab?: T;
            };
        required?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?: T;
  uploads?:
    | T
    | {
        field?: T;
        files?: T;
        id?: T;
      };
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  logo?: (number | null) | Media;
  links?:
    | {
        text: string;
        customHref?: boolean | null;
        href?: string | null;
        linkType?:
          | (
              | "home"
              | "blog"
              | "page"
              | "blog-post"
              | "privacy-policy"
              | "cookie-policy"
              | "terms-and-conditions"
            )
          | null;
        page?: {
          relationTo: "pages";
          value: number | Page;
        } | null;
        blogPost?: {
          relationTo: "blog-posts";
          value: number | BlogPost;
        } | null;
        newTab?: boolean | null;
        dropdown?: boolean | null;
        clickable?: boolean | null;
        sublinks?:
          | {
              text: string;
              customHref?: boolean | null;
              href?: string | null;
              linkType?:
                | (
                    | "home"
                    | "blog"
                    | "page"
                    | "blog-post"
                    | "privacy-policy"
                    | "cookie-policy"
                    | "terms-and-conditions"
                  )
                | null;
              page?: {
                relationTo: "pages";
                value: number | Page;
              } | null;
              blogPost?: {
                relationTo: "blog-posts";
                value: number | BlogPost;
              } | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  showButton?: boolean | null;
  button?: {
    variant:
      | "purpleButton"
      | "whiteButton"
      | "darkButton"
      | "transparentButton";
    text: string;
    customHref?: boolean | null;
    href?: string | null;
    linkType?:
      | (
          | "home"
          | "blog"
          | "page"
          | "blog-post"
          | "privacy-policy"
          | "cookie-policy"
          | "terms-and-conditions"
        )
      | null;
    page?: {
      relationTo: "pages";
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: "blog-posts";
      value: number | BlogPost;
    } | null;
    newTab?: boolean | null;
    centered?: boolean | null;
  };
  slideOutMenu?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  Paragraph?: string | null;
  email?: {
    text?: string | null;
  };
  phone?: {
    text?: string | null;
  };
  address?: {
    text?: string | null;
    href?: string | null;
  };
  quickLinks?:
    | {
        text: string;
        customHref?: boolean | null;
        href?: string | null;
        linkType?:
          | (
              | "home"
              | "blog"
              | "page"
              | "blog-post"
              | "privacy-policy"
              | "cookie-policy"
              | "terms-and-conditions"
            )
          | null;
        page?: {
          relationTo: "pages";
          value: number | Page;
        } | null;
        blogPost?: {
          relationTo: "blog-posts";
          value: number | BlogPost;
        } | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        text: string;
        customHref?: boolean | null;
        href?: string | null;
        linkType?:
          | (
              | "home"
              | "blog"
              | "page"
              | "blog-post"
              | "privacy-policy"
              | "cookie-policy"
              | "terms-and-conditions"
            )
          | null;
        page?: {
          relationTo: "pages";
          value: number | Page;
        } | null;
        blogPost?: {
          relationTo: "blog-posts";
          value: number | BlogPost;
        } | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  socialMediaLinks?:
    | {
        icon?: (number | null) | Media;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        text: string;
        customHref?: boolean | null;
        href?: string | null;
        linkType?:
          | (
              | "home"
              | "blog"
              | "page"
              | "blog-post"
              | "privacy-policy"
              | "cookie-policy"
              | "terms-and-conditions"
            )
          | null;
        page?: {
          relationTo: "pages";
          value: number | Page;
        } | null;
        blogPost?: {
          relationTo: "blog-posts";
          value: number | BlogPost;
        } | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  companyDetails?: {
    kvk?: string | null;
    vat?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  blocks?:
    | (
        | TextAndImageBlock
        | FormBlock
        | TextBlock
        | CardsBlock
        | VisualBlock
        | ProcessBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically set
   */
  url?: string | null;
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  heading?: string | null;
  paragraph?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically set
   */
  url?: string | null;
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: number;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically set
   */
  url?: string | null;
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy".
 */
export interface CookiePolicy {
  id: number;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically set
   */
  url?: string | null;
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions".
 */
export interface TermsAndCondition {
  id: number;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically set
   */
  url?: string | null;
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  logo?: T;
  links?:
    | T
    | {
        text?: T;
        customHref?: T;
        href?: T;
        linkType?: T;
        page?: T;
        blogPost?: T;
        newTab?: T;
        dropdown?: T;
        clickable?: T;
        sublinks?:
          | T
          | {
              text?: T;
              customHref?: T;
              href?: T;
              linkType?: T;
              page?: T;
              blogPost?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  showButton?: T;
  button?:
    | T
    | {
        variant?: T;
        text?: T;
        customHref?: T;
        href?: T;
        linkType?: T;
        page?: T;
        blogPost?: T;
        newTab?: T;
        centered?: T;
      };
  slideOutMenu?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  Paragraph?: T;
  email?:
    | T
    | {
        text?: T;
      };
  phone?:
    | T
    | {
        text?: T;
      };
  address?:
    | T
    | {
        text?: T;
        href?: T;
      };
  quickLinks?:
    | T
    | {
        text?: T;
        customHref?: T;
        href?: T;
        linkType?: T;
        page?: T;
        blogPost?: T;
        newTab?: T;
        id?: T;
      };
  services?:
    | T
    | {
        text?: T;
        customHref?: T;
        href?: T;
        linkType?: T;
        page?: T;
        blogPost?: T;
        newTab?: T;
        id?: T;
      };
  socialMediaLinks?:
    | T
    | {
        icon?: T;
        href?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        text?: T;
        customHref?: T;
        href?: T;
        linkType?: T;
        page?: T;
        blogPost?: T;
        newTab?: T;
        id?: T;
      };
  companyDetails?:
    | T
    | {
        kvk?: T;
        vat?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        "text-and-image-block"?: T | TextAndImageBlockSelect<T>;
        "form-block"?: T | FormBlockSelect<T>;
        "text-block"?: T | TextBlockSelect<T>;
        "cards-block"?: T | CardsBlockSelect<T>;
        "visual-block"?: T | VisualBlockSelect<T>;
        "process-block"?: T | ProcessBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  url?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  heading?: T;
  paragraph?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  url?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  url?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy_select".
 */
export interface CookiePolicySelect<T extends boolean = true> {
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  url?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions_select".
 */
export interface TermsAndConditionsSelect<T extends boolean = true> {
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  url?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ("publish" | "unpublish") | null;
    locale?: string | null;
    global?:
      | (
          | "home"
          | "blog"
          | "privacy-policy"
          | "cookie-policy"
          | "terms-and-conditions"
        )
      | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
